### ISSUE TITLE
/MNIST_data; Permission denied

### ISSUE THREAD

**Issue by kbrown** [Tathagatd96/Deep-Autoencoder-using-Tensorflow#1]
I don't have access to "/"

python3 Stacked_AutoEncoder.py 
tensorflow.python.framework.errors_impl.PermissionDeniedError: /MNIST_data; Permission denied

**Comment by ghost** [comment]
Miss typo. Change "/MNIST_data/" into "MNIST_data/". Read code before raising any issue.
